### ISSUE TITLE
Compilation error with TypeScript

### ISSUE THREAD

**Issue by pash90** [formatjs/formatjs-old#186]
**Which package?**
`@formatjs/intl-relativetimeformat`

**Describe the bug**
`A rest element cannot contain a binding pattern.`

**To Reproduce**

1. Follow the instructions to install the npm package into your project
2. Compile the project
3. See error

**Expected behavior**
No errors should be displayed in the terminal

**Screenshots**
![image](https://user-images.githubusercontent.com/24995648/64832239-76149700-d61c-11e9-80b4-de13e80d01f3.png)

**Desktop (please complete the following information):**

- OS: macOS Mojave (10.14.6)
- Browser: Safari, Chrome, Firefox

**Smartphone (please complete the following information):**
No tested on mobile since my project is desktop only.

**Additional context**

**Comment by longlho** [comment]
TS 3.2.2 is pretty old. Does it pass in newer TS?

**Comment by pash90** [comment]
@longlho I'll check and get back to you 👍

**Comment by pash90** [comment]
@longlho Yep worked with `typescript@3.6.3`. Closing this issue. Thanks!
